import torch as th

ROTATE_MULTIPLIER = 180.
SCALE_ADDITION = 1.1
SCALE_MULTIPLIER = 1.0

TRANSLATE_RANGE_MULT = 0.75
SCALE_RANGE_MULT = 0.75
ROTATE_RANGE_MULT = 180. * 0.75


VALIDATION_THRESHOLD = 0.025
VALIDATION_THRESHOLD_DIFF = 0.05

TRANSFORM_SAMPLING_RATE = dict(translate=0.8, scale=0.6, rotate=0.4)
MIRROR_SAMPLING_RATE = 0.15
HIER_TFORM_RATE = 0.4

PRIMITIVE_OCCUPANCY_MIN_THRES = 0.025
PRIMITIVE_OCCUPANCY_MAX_THRES = 0.4
BBOX_LIMIT = 0.95

CONVERSION_DELTA = 1e-9# th.finfo(th.float16).eps

TRANSLATE_MIN = -1 + CONVERSION_DELTA
TRANSLATE_MAX = 1 - CONVERSION_DELTA
SCALE_MIN = 0.1 + CONVERSION_DELTA
SCALE_MAX = 2.1 - CONVERSION_DELTA
ROTATE_MIN = 180 * (-1 + CONVERSION_DELTA) 
ROTATE_MAX = 180 * (1 - CONVERSION_DELTA)
DRAW_MIN = CONVERSION_DELTA
DRAW_MAX = 1 - CONVERSION_DELTA

SA_FLOAT_MIN = CONVERSION_DELTA
SA_FLOAT_MAX = 1.0 - CONVERSION_DELTA